[build-system]

requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2", "wheel"]

build-backend = 'setuptools.build_meta'

[project]
name = "carsus"
description = "Atomic Database for Astronomy"
readme = { file = "README.rst", content-type = "text/x-rst" }
authors = [
    { name = "TARDIS Collaboration", email = "wkerzendorf@gmail.com" },
]
license = { text = "BSD 3-Clause" }
requires-python = ">=3.6"
dependencies = [
    "astropy",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://tardis-sn.github.io/carsus"

[project.optional-dependencies]
test = [
    "pytest-astropy",
]
docs = [
    "sphinx-astropy",
    "tomli; python_version < '3.11'",
]

[tool.setuptools]
zip-safe = false
license-files = ["licenses/LICENSE.rst"]

[tool.setuptools.packages.find]

[tool.setuptools.package-data]
carsus = ["data/*"]
"carsus.tests" = ["data/*"]

[tool.setuptools_scm]
write_to = "carsus/version.py"
write_to_template = """
# Note that we need to fall back to the hard-coded version if either
# setuptools_scm can't be imported or setuptools_scm can't determine the
# version, so we catch the generic 'Exception'.
try:
    from setuptools_scm import get_version
    version = get_version(root='..', relative_to=__file__)
except Exception:
    version = '{version}'
"""

[tool.ruff]
line-length = 80
lint.select = ["ALL"]
lint.ignore = [  # NOTE: non-permanent exclusions should be added to `.ruff.toml` instead.

    # flake8-builtins (A) : shadowing a Python built-in.
    # New ones should be avoided and is up to maintainers to enforce.
    "A00",

    # flake8-annotations (ANN)
    "ANN101",  # No annotation for `self`.
    "ANN102",  # No annotation for `cls`.

    # flake8-bugbear (B)
    "B008",  # FunctionCallArgumentDefault

    # flake8-commas (COM)
    "COM812",  # TrailingCommaMissing
    "COM819",  # TrailingCommaProhibited

    # pydocstyle (D)
    # Missing Docstrings
    "D105",  # Missing docstring in magic method. Don't check b/c class docstring.
    # Whitespace Issues
    "D200",  # FitsOnOneLine
    # Docstring Content Issues
    "D410",  # BlankLineAfterSection. Using D412 instead.
    "D400",  # EndsInPeriod.  NOTE: might want to revisit this.

    # pycodestyle (E, W)
    "E711",  # NoneComparison  (see unfixable)
    "E741",  # AmbiguousVariableName. Physics variables are often poor code variables

    # flake8-fixme (FIX)
    "FIX002",  # Line contains TODO | notes for improvements are OK iff the code works

    # ISC001 shouldn't be used with ruff format
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "ISC001",

    # pep8-naming (N)
    "N803",  # invalid-argument-name. Physics variables are often poor code variables
    "N806",  # non-lowercase-variable-in-function. Physics variables are often poor code variables

    # pandas-vet (PD)
    "PD",

    # flake8-self (SLF)
    "SLF001", # private member access

    # flake8-todos (TD)
    "TD002",  # Missing author in TODO

    # Ruff-specific rules (RUF)
    "RUF005",  # unpack-instead-of-concatenating-to-collection-literal -- it's not clearly faster.
]

[tool.ruff.lint.extend-per-file-ignores]
".github/workflows/*.py" = ["INP001"]
"test_*.py" = [
    "B018",  # UselessExpression
    "D",  # pydocstyle
    "S101",  # Use of assert detected
]
".pyinstaller/*.py" = ["INP001"]  # Not a package.
"conftest.py" = ["INP001"]  # Part of configuration, not a package.
"docs/*.py" = [
    "INP001",  # implicit-namespace-package. The examples are not a package.
]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true
mypy-init-return = true

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.flake8-type-checking]
exempt-modules = []

[tool.ruff.lint.isort]
known-first-party = ["carsus"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
testpaths = ["carsus", "docs"]
text_file_format = "rst"
filterwarnings = [
    "ignore::DeprecationWarning",
]
markers = [
    "with_regression_data: mark tests as needing regression data path to run",
    "remote_data: mark tests as needing network access to run",
]

[tool.coverage.run]
omit = [
    "carsus/_astropy_init*",
    "carsus/conftest.py",
    "carsus/*setup_package*",
    "carsus/tests/*",
    "carsus/*/tests/*",
    "carsus/extern/*",
    "carsus/version*",
    "*/carsus/_astropy_init*",
    "*/carsus/conftest.py",
    "*/carsus/*setup_package*",
    "*/carsus/tests/*",
    "*/carsus/*/tests/*",
    "*/carsus/extern/*",
    "*/carsus/version*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "except ImportError",
    "raise AssertionError",
    "raise NotImplementedError",
    "def main\\(.*\\):",
    "pragma: py{ignore_python_version}",
    "def _ipython_key_completions_",
    "def __repr__",
    "if self\\.debug",
    "if 0:",
    "if __name__ == .__main__.:",
]
omit = [
    "*__init__*",
    "*_astropy_init*",
    "*version*",
    "*tests*",
    "*conftest*",
    "*setup_package*",
]
ignore_errors = true

[tool.coverage.html]
directory = "coverage_html_report"

[tool.carsus.docs]
edit_on_github = false
github_project = "tardis-sn/carsus"

[tool.git-cliff.changelog]
header = "## Changelog\n\n"
body = """
### {{version}} ({{ timestamp | date(format="%Y/%m/%d %H:%M", timezone="America/New_York") }})
{% for commit in commits %}
    {%- if commit.github.pr_number -%}
  - [{{commit.github.pr_number}}](https://github.com/tardis-sn/carsus/pull/{{commit.github.pr_number}}) {{ commit.github.pr_title | split(pat="\n") | first | trim }} ({{commit.github.pr_number}}) (@{{ commit.github.username }})
    {% endif -%}
{%- endfor -%}
"""
trim = true
footer = "<!-- generated by git-cliff -->"

[tool.git-cliff.git]
conventional_commits = false
filter_unconventional = false
sort_commits = "newest"

[tool.git-cliff.remote.github]
owner = "tardis-sn"
repo = "carsus"
