name: docs

on:
  push:
    branches:
    - master

  schedule:
    - cron: '10 0 * * 0'

  workflow_dispatch:  # Manual trigger

env:
  XUVTOP: /tmp/chianti
  CHIANTI_DB_VERSION: 9.0.1
  CHIANTI_DATA_URL: https://download.chiantidatabase.org
  CMFGEN_DATA_URL: http://kookaburra.phyast.pitt.edu/hillier/cmfgen_files/atomic_data_15nov16.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Chianti database
        run: |
            mkdir ${{ env.XUVTOP }}
            wget -q $CHIANTI_DB_URL -O ${{ env.XUVTOP }}/chianti_db.tar.gz
            tar -zxvf ${{ env.XUVTOP }}/chianti_db.tar.gz -C ${{ env.XUVTOP }}
        env:
          CHIANTI_DB_URL: ${{ env.CHIANTI_DATA_URL }}/CHIANTI_v${{ env.CHIANTI_DB_VERSION }}_database.tar.gz

      - name: Download CMFGEN database
        run: |
            wget -q $CMFGEN_DATA_URL -O /tmp/atomic.tar.gz
            tar -zxvf /tmp/atomic.tar.gz -C /tmp

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            environment-file: carsus_env3.yml
            activate-environment: carsus
            use-mamba: true

      - name: Install package
        shell: bash -l {0}
        run: python setup.py install

      - name: Build documentation
        shell: bash -l {0}
        run: cd docs/; make html

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
          force_orphan: true
